version: '3'
services:
  bind:
    build: .
    container_name: isc-bind-server
    image: isc-bind-server
    network_mode: "host"
    volumes:
      - "../bind/usr:/usr/share/dns/"
      - "../bind/etc:/etc/bind"
      - "../bind/var/cache:/var/cache/bind"
      - "../bind/var/lib:/var/lib/bind"
      - "../bind/var/log:/var/log"
    restart: always
