version: "3"
services:
  bind:
    image: ghcr.io/spacerouter/isc-bind-server:latest
    container_name: isc-bind-server
    network_mode: "host"
    volumes:
      - "/etc/sr/bind/data/usr:/usr/share/dns/"
      - "/etc/sr/bind/data/etc:/etc/bind"
      - "/etc/sr/bind/data/var/cache:/var/cache/bind"
      - "/etc/sr/bind/data/var/lib:/var/lib/bind"
      - "/etc/sr/bind/data/var/log:/var/log"
    restart: always
