version: '3'
services:
  dhcp:
    build: .
    container_name: isc-bind-server
    image: isc-bind-server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
    volumes:
      - "../bind/usr:/usr/share/dns/"
      - "../bind/etc:/etc/bind"
      - "../bind/var/cache:/var/cache/bind"
      - "../bind/var/lib:/var/lib/bind"
      - "../bind/var/log:/var/log"
    restart: always
